# Generated by Django 2.1.5 on 2021-02-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default=True, max_length=256)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('title_unique', models.CharField(max_length=255)),
                ('description_unique', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('h1', models.CharField(blank=True, default=True, max_length=255)),
                ('h2', models.CharField(blank=True, default=True, max_length=255)),
                ('broken_link', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
