# Generated by Django 2.1.5 on 2021-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='broken_link',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='description',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='description_unique',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='keywords',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='title',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='title_unique',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='url',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
