# Generated by Django 2.1.5 on 2021-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_deletewhilesaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='facebook',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='results',
            name='google',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='results',
            name='instagram',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='results',
            name='vk',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='results',
            name='yandex',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='base_url',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='date_add',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='h1',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='results',
            name='h2',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
